<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Common\Infrastructure\Persistence\Configurations\**" />
    <EmbeddedResource Remove="Common\Infrastructure\Persistence\Configurations\**" />
    <None Remove="Common\Infrastructure\Persistence\Configurations\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Auth\Domain\" />
    <Folder Include="Auth\Infrastructure\" />
    <Folder Include="Auth\Application\" />
    <Folder Include="Common\Infrastructure\Persistence\Migrations\" />
    <Folder Include="Common\Domain\" />
    <Folder Include="Common\Error\" />
    <Folder Include="Common\Interfaces\" />
  </ItemGroup>

</Project>
